# Generated by Django 6.0.2 on 2026-02-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeimage",
            name="label",
            field=models.CharField(
                choices=[
                    ("Inside", "Inside"),
                    ("Outside", "Outside"),
                    ("Drink", "Drink"),
                    ("Food", "Food"),
                    ("Menu", "Menu"),
                    ("Amenities", "Amenities"),
                ],
                default="Inside",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="opening_hours",
            field=models.JSONField(
                blank=True, default=dict, help_text="Structured operating hours"
            ),
        ),
    ]
